import { Platform } from 'react-native'
import type {
  AppInfoItem,
  BugReport,
  BugReportSeverity,
  LogEntry,
  NetworkEntry,
} from './types'
import { LogLevel } from './types'

// ─── Report Composition ──────────────────────────────────────────────────────

const SEVERITY_LABELS: Record<BugReportSeverity, string> = {
  low: '🟢 Low',
  medium: '🟡 Medium',
  high: '🟠 High',
  critical: '🔴 Critical',
}

function formatTimestamp(ts: number): string {
  const d = new Date(ts)
  return d.toISOString().replace('T', ' ').substring(0, 19)
}

function formatLogLevel(level: LogLevel): string {
  switch (level) {
    case LogLevel.error:
      return '❌ ERROR'
    case LogLevel.warn:
      return '⚠️ WARN'
    case LogLevel.info:
      return 'ℹ️ INFO'
    case LogLevel.debug:
      return '🔍 DEBUG'
    default:
      return '📝 LOG'
  }
}

export function formatDeviceInfoForReport(items: AppInfoItem[]): string {
  if (items.length === 0) return ''
  const lines = items.map(i => `- **${i.label}**: ${i.value}`)
  return `## 📱 Device Info\n\n${lines.join('\n')}\n`
}

export function formatLogsForReport(logs: LogEntry[]): string {
  if (logs.length === 0) return ''
  const lines = logs.map(
    l => `\`${formatTimestamp(l.timestamp)}\` ${formatLogLevel(l.level)} ${l.message}`,
  )
  return `## 📋 Console Logs (${logs.length})\n\n\`\`\`\n${lines.join('\n')}\n\`\`\`\n`
}

export function formatNetworkForReport(entries: NetworkEntry[]): string {
  if (entries.length === 0) return ''
  const lines = entries.map(e => {
    const status = e.status ?? '⏳'
    const duration = e.duration ? `${e.duration}ms` : '...'
    return `- \`${e.method}\` ${e.url} → ${status} (${duration})`
  })
  return `## 🌐 Network Activity (${entries.length})\n\n${lines.join('\n')}\n`
}

export function formatStateForReport(state: Record<string, unknown>): string {
  try {
    const json = JSON.stringify(state, null, 2)
    // Truncate if too large
    const truncated = json.length > 5000 ? json.substring(0, 5000) + '\n... (truncated)' : json
    return `## 🌳 State Snapshot\n\n\`\`\`json\n${truncated}\n\`\`\`\n`
  } catch {
    return `## 🌳 State Snapshot\n\n\`[Could not serialize state]\`\n`
  }
}

export function composeBugReport(report: BugReport): string {
  const sections: string[] = []

  sections.push(`# 🐛 Bug Report: ${report.title}\n`)
  sections.push(`**Severity**: ${SEVERITY_LABELS[report.severity]}`)
  sections.push(`**Reported**: ${formatTimestamp(report.timestamp)}`)
  sections.push(`**Platform**: ${Platform.OS} ${Platform.Version}\n`)

  if (report.description) {
    sections.push(`## Description\n\n${report.description}\n`)
  }

  if (report.deviceInfo.length > 0) {
    sections.push(formatDeviceInfoForReport(report.deviceInfo))
  }

  if (report.logs.length > 0) {
    sections.push(formatLogsForReport(report.logs))
  }

  if (report.networkEntries.length > 0) {
    sections.push(formatNetworkForReport(report.networkEntries))
  }

  if (report.state && Object.keys(report.state).length > 0) {
    sections.push(formatStateForReport(report.state))
  }

  if (report.screenshotUri) {
    sections.push(`## 📸 Screenshot\n\nAttached: ${report.screenshotUri}\n`)
  }

  sections.push('---\n*Generated by rn-backstage*')

  return sections.join('\n')
}

// ─── Webhook Submission ──────────────────────────────────────────────────────

export async function submitToWebhook(
  webhookUrl: string,
  report: BugReport,
): Promise<{ success: boolean; error?: string }> {
  try {
    const body: Record<string, unknown> = {
      title: report.title,
      description: report.description,
      severity: report.severity,
      platform: Platform.OS,
      platformVersion: String(Platform.Version),
      timestamp: report.timestamp,
      deviceInfo: report.deviceInfo,
      logs: report.logs.map(l => ({
        level: l.level,
        message: l.message,
        timestamp: l.timestamp,
      })),
      networkEntries: report.networkEntries.map(e => ({
        method: e.method,
        url: e.url,
        status: e.status,
        duration: e.duration,
      })),
    }

    if (report.state) {
      body.state = report.state
    }

    if (report.screenshotUri) {
      body.screenshotUri = report.screenshotUri
    }

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })

    if (!response.ok) {
      return { success: false, error: `HTTP ${response.status}` }
    }

    return { success: true }
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    }
  }
}

// ─── Device Info Builder ─────────────────────────────────────────────────────

export function buildDeviceInfo(
  appVersion?: string,
  buildNumber?: string,
  bundleId?: string,
  extraInfo: AppInfoItem[] = [],
): AppInfoItem[] {
  const info: AppInfoItem[] = [
    { label: 'Platform', value: `${Platform.OS} ${Platform.Version}` },
  ]

  if (appVersion) info.push({ label: 'App Version', value: appVersion })
  if (buildNumber) info.push({ label: 'Build Number', value: buildNumber })
  if (bundleId) info.push({ label: 'Bundle ID', value: bundleId })

  return [...info, ...extraInfo]
}
